# Dockerfile (VERSION ULTRA-ROBUSTA)

# Usamos la imagen base de Python 3.10
FROM python:3.10

# Establece el directorio de trabajo
WORKDIR /app

# Instala las dependencias necesarias de Chrome/Chromium y su driver
# El uso de apt-get update y el & separa los comandos lo hace más fiable
RUN apt-get update \
    && apt-get install -y --no-install-recommends \
    chromium \
    chromium-driver \
    libnss3 \
    libgconf-2-4 \
    --fix-missing \
    && rm -rf /var/lib/apt/lists/*

# CRÍTICO: Asegura permisos de ejecución
# (Aunque Chromium ya debería tenerlos, esto elimina dudas)
RUN chmod +x /usr/bin/chromedriver
RUN chmod +x /usr/bin/chromium

# Configura variables de entorno para las rutas (ya que usamos la instalación estándar)
ENV CHROME_DRIVER_PATH /usr/bin/chromedriver
ENV CHROMIUM_PATH /usr/bin/chromium

# Copia los requisitos e instala las dependencias de Python
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Copia el resto del código
COPY . .

# Comando de inicio
EXPOSE 8000
CMD ["gunicorn", "--bind", "0.0.0.0:8000", "app:app"]
